### ISSUE TITLE
Datasheet Says CLIC Not CLINT

### ISSUE THREAD

**Issue by jrtc27** [starfive-tech/beaglev_doc#7]
2.1.2. SiFive U74 Dual Core says "CLIC for timer and software interrupts", but that sounds like a CLINT, and the DTS says it's a CLINT. Only the E24 uses a CLIC (and thank god for that given that spec is not ratified and is going through churn; OSes would _not_ take kindly to having to support some random CLIC draft for the RV64 cores).

**Comment by pdp7** [comment]
@jrtc27 hello, thank you for taking the time to open this issue.  This was noted in #2 and the technical writer was alerted to the issue.  However, I should have left that issue open until the new revised PDF is ready.  I am going to close this issue and leave #2 open until there is new revision of datasheet.

**Comment by jrtc27** [comment]
Ah, should've searched through all issues, not just open ones.
